ARG RADICLE_VERSION
ARG ALPINE_VERSION
FROM quay.io/radicle_garden/heartwood:$RADICLE_VERSION as heartwood

FROM alpine:${ALPINE_VERSION}
RUN apk add git

ARG RADICLE_VERSION
ARG PLATFORM
ENV RADICLE_USER_ID=11011 RADICLE_GROUP_ID=11011

COPY --from=heartwood /builds/radicle-$RADICLE_VERSION-$PLATFORM.tar.xz .

RUN tar xf radicle-$RADICLE_VERSION-$PLATFORM.tar.xz

RUN mv radicle-$RADICLE_VERSION-$PLATFORM/bin/rad /usr/local/bin/ && \
    mv radicle-$RADICLE_VERSION-$PLATFORM/bin/git-remote-rad /usr/local/bin/ && \
    mv radicle-$RADICLE_VERSION-$PLATFORM/bin/radicle-node /usr/local/bin/

RUN rm -rf radicle-$RADICLE_VERSION-$PLATFORM/

ADD https://minio-api.radworks.garden/radworks-releases/radicle-healthcheck/v0.1.0/radicle-healthcheck_v0.1.0_x86_64-unknown-linux-musl /usr/local/bin/radicle-healthcheck
RUN chmod +x /usr/local/bin/radicle-healthcheck

# Create a non-root user
RUN addgroup -S radicle -g $RADICLE_GROUP_ID  && adduser -S radicle -G radicle -u $RADICLE_USER_ID

# Change ownership of necessary directories/files
RUN chown -R radicle:radicle /home/radicle /usr/local/bin/radicle-node /usr/local/bin/rad  /usr/local/bin/git-remote-rad

USER radicle

WORKDIR /home/radicle

EXPOSE 8776

ENTRYPOINT ["/usr/local/bin/radicle-node"]
