when:
  - path:
      include: [ 'Containerfile', '.woodpecker/container_image.yaml' ]

steps:

  - name: build-image
    image: woodpeckerci/plugin-docker-buildx:5.2.1
    settings:
      platforms: linux/amd64
      repo: quay.io/radicle_garden/frontend
      registry: quay.io
      dry-run: true
      dockerfile: Containerfile
      env_file:
        - .env.example
    when:
      - event: pull_request

  - name: publish-image
    image: woodpeckerci/plugin-docker-buildx:5.2.1
    settings:
      platforms: linux/amd64
      repo: quay.io/radicle_garden/frontend
      registry: quay.io
      dockerfile: Containerfile
      env_file:
        - .env.example
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    when:
      - event: manual
      - event: push
        branch: main
